
import { AppComponent } from "@/components/App";
      
// THIS FILE IS AUTOGENERATED - DO NOT MODIFY- THIS FILE IS AUTOGENERATED - DO NOT MODIFY only run again in scripts/make-pages.js
      
export default async function page() {
    return <AppComponent currentName={"עטיל"} />;
}
            
            